### ISSUE TITLE
[bug] Unhelpful oauth error for unsupported grant type

### ISSUE THREAD

**Issue by russss** [superseriousbusiness/gotosocial#1546]
### Describe the bug with a clear and concise description of what the bug is.

When I POST to `/oauth/token` with a `grant_type` of `password` (which is unsupported), I get the following rather unhelpful error:

```json
{
"error": "invalid_request"
"error_description": "Bad Request: could not validate token request: invalid_request: If you arrived at this error during a login/oauth flow, please try clearing your session cookies and logging in again; if problems persist, make sure you're using the correct credentials"
}
```

This is probably going to be a relatively common failure so it would be nice to have a more informative error message.

### What's your GoToSocial Version?

0.7.1

### GoToSocial Arch

amd64

**Comment by tsmethurst** [comment]
Ack, i'll see if there's an elegant way to do this

**Comment by daenney** [comment]
In https://github.com/superseriousbusiness/gotosocial/blob/main/internal/oauth/server.go#L97-L100 we set the supported grant types. That should be accessible in the handler so we could check if the provided grant type matches one of those?

**Comment by daenney** [comment]
@russss Did you provide a `username` and `password` as part of the request you did? I'm trying to trace the code path, but the only way I see that it would return an `invalid_request` instead of an `invalid_grant_type` is if either of those two weren't provided.

**Comment by russss** [comment]
Ah yes sorry - I definitely was providing a username and password. It confused me too. Here are the parameters I was passing:

```[('username', '<redacted>'), ('password', '<redacted>'), ('redirect_uri', 'urn:ietf:wg:oauth:2.0:oob'), ('grant_type', 'password'), ('client_id', '<redacted>'), ('client_secret', '<redacted>'), ('scope', 'read write follow push')]```

**Comment by tsmethurst** [comment]
`fmt.Println()` IS a proper debugger :D

**Comment by daenney** [comment]
Alright, I think I'm going insane.

I've booted up a testrig, and I'm doing the following `curl` request:
```
$ curl -X POST 'http://localhost:8080/oauth/token' --header 'Content-Type: application/x-www-form-urlencoded' \
                                         --data-urlencode 'grant_type=password' \
                                         --data-urlencode 'username=user' \
                                         --data-urlencode 'password=password' \
                                         --data-urlencode 'scope=*' \
                                         --data-urlencode 'client_id=test' \
                                         --data-urlencode 'client_secret=test' \
                                         --data-urlencode 'redirect_uri=urn:ietf:wg:oauth:2.0:oob'
```

Our journey starts at: https://github.com/superseriousbusiness/gotosocial/blob/9cfb69f75d3eb422e61de14d5090ea96d541bae9/internal/oauth/server.go#L131-L134, I get an error there.

Jumping into it, we go to https://github.com/superseriousbusiness/gotosocial/blob/9cfb69f75d3eb422e61de14d5090ea96d541bae9/vendor/github.com/superseriousbusiness/oauth2/v4/server/server.go#L305-L364.

Specifically and unsurprisingly, we end up in https://github.com/superseriousbusiness/gotosocial/blob/9cfb69f75d3eb422e61de14d5090ea96d541bae9/vendor/github.com/superseriousbusiness/oauth2/v4/server/server.go#L339-L344.

What happens there is that, according to my debugger, `scope` is properly set up to be `"*"` but the `username` and `password` values end up empty. I don't get _how_ that happens though, but this is what I see:

```
r.Form: net/url.Values ["grant_type": ["password"], "client_id": ["test"], "client_secret": ["test"], "redirect_uri": ["urn:ietf:wg:oauth:2.0:oob"], "scope": ["*"], ]
```
Versus:
```
r.PostForm: net/url.Values ["grant_type": ["password"], "username": ["user"], "password": ["password"], "scope": ["*"], "client_id": ["test"], "client_secret": ["test"], "redirect_uri": ["urn:ietf:wg:oauth:2.0:oob"], ]
```

The username and password just disappear somehow?

Arguably we should never get there. I think in our original handler we should check if the `grant_type` matches one of the ones we have enabled and if not we don't even have to bother with jumping in the oauth library at all.
```

**Comment by daenney** [comment]
Alternatively, come to think of it, the `ValidationTokenRequest` ought to check the grant type. 

I'm also a bit more confused because part of the help text that that return ought to be generating seems to have gone missing based on the original bug report. Which makes me wonder if I'm triggering some other issue and what I'm seeing may be a side effect of running the testrig.

**Comment by tsmethurst** [comment]
I merged your pr on the oauth library :) Also made an updated version of the library (merging changes from upstream too) -- https://github.com/superseriousbusiness/oauth2/releases/tag/v4.5.2-SSB -- so now a version bump pr on the main gotosocial repo should fix this!

**Comment by daenney** [comment]
Cool, so now at least the error is:

```
{"error":"unsupported_grant_type","error_description":"Bad Request: could not validate token request: unsupported_grant_type: If you arrived at this error during a login/oauth flow, please try clearing your session cookies and logging in again; if problems persist, make sure you're using the correct credentials"}
```

It's still not the most user friendly thing, but at least the `unsupported_grant_type` should give folks a decent clue.
