### ISSUE TITLE
[bug] Profile search issues with Akkoma

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2004]
### Describe the bug with a clear and concise description of what the bug is.

I think there’s a bugreport about this somewhere, but I cannot find it any more.

IIRC it was known that GtS users cannot search for users on Akkoma by using the `https://«fqdn»/users/«username»` syntax **but** searching for them via the `@«username»@«fqdn»` syntax works.

Today’s data point is an Akkoma user having the same problem searching for a GtS user, so the same thing is also true in reverse.

### What's your GoToSocial Version?

0.9.0 git-282be6f

### GoToSocial Arch

amd64 binary

### Anything else we need to know?

If this also applies to other instance softwares, we probably should reflect that in the title by updating it.

**Comment by tsmethurst** [comment]
Can you give any details about which user was searching for which? Or at least which instance the akkoma user was on? Then we can start trying to replicate this, hopefully

**Comment by mirabilos** [comment]
Is there any way to give these privately? (I could just DM you or the team account on Fedi.)

**Comment by mirabilos** [comment]
Some extra _public_ info:

When searching an Akkoma user from Gts per `https://` then, if the user is already known (e.g. from searching via `@…`, communicating with them, etc.) it succeeds, but if not, there is a 500 error:

    timestamp="20/07/2023 16:44:01.585" func=middleware.Logger.func1.1 level=ERROR latency=128.038989ms userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" method=GET statusCode=500 path=/api/v2/search error="Error #01: error looking up status: enrichStatus: error resolving statusable from data for account https://«domain»/«user»: ResolveStatusable: error unmarshalling bytes into json: invalid character '<' looking for beginning of value\n" requestID=67f2yx4904001y44ccm0 msg="Internal Server Error: wrote 54B"

**Comment by tsmethurst** [comment]
Ahhh right thank you for the additional logs! It looks like akkoma (or at least, that particular akkoma instance) is not serving activitypub at the requested endpoint, but is serving HTML.

I wonder, could you try updating to the latest release candidate (0.10.0-rc3) and see if this is still an issue? It's worth doing anyway, but also we changed some behavior related to search and whatnot in the new version, so the bug may either manifest differently or not occur at all. Release candidate is right here: https://github.com/superseriousbusiness/gotosocial/releases/tag/v0.10.0-rc3

**Comment by mirabilos** [comment]
OK, I’ll do that (I was planning to hold out until the release, but until then…)

The other thing was an Akkoma 3.9.3 user searching for users on my instance from URL, which failed, but from `@` succeeded.

**Comment by tsmethurst** [comment]
> The other thing was an Akkoma 3.9.3 user searching for users on my instance from URL, which failed, but from @ succeeded.

This one should be fixed by https://github.com/superseriousbusiness/gotosocial/pull/1954, at least i bloody hope it's fixed

**Comment by mirabilos** [comment]
I’ve asked the Akkoma user to find one user on my instance for which it still fails, before the upgrade, to be able to verify that.

**Comment by mirabilos** [comment]
Searching for an Akkoma user by `https://` from the updated GtS has a slightly different 500 message but still the error:

    timestamp="20/07/2023 22:53:43.589" func=middleware.Logger.func1.1 level=ERROR latency=390.808954ms userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" method=GET statusCode=500 path=/api/v2/search error="Error #01: Get: error searching by URI: byURI: error looking up https://«domain»/«user» as account: enrichAccount: error resolving accountable from data for account https://«domain»/«user»: ResolveAccountable: error unmarshalling bytes into json: invalid character '<' looking for beginning of value\n" requestID=ksar4xc9040010yhajr0 msg="Internal Server Error: wrote 54B"

According to another Akkoma user, searching for GtS users their instance does *not* already know about by `https://` is also still not possible. The log says:

    timestamp="20/07/2023 22:54:23.379" func=middleware.Logger.func1.1 level=INFO latency=166.053485ms userAgent="Akkoma 3.9.3; https://… <…@…>" method=GET statusCode=200 path=/@useronmyinstance requestID=xkrr4xc9040018x1schg msg="OK: wrote 1.93kiB"

I gave them `https://myinstance.example.com/@useronmyinstance` to search for, which works both in the web view and when I search for it in my own Semaphor…oh wait, I knew about this…
… when I search for it from a Pinafore instance logged in as one of the other bot accounts on my instance, i.e. who also didn’t know about it yet.

So, issues in both directions are still open.

**Comment by tsmethurst** [comment]
Hmm, the second log line you posted shows that GtS *is* serving the request coming from akkoma with no issue, and the length of the response suggests it's serving an ActivityPub representation as expected, rather than HTML. Some logs from that akkoma instance would be helpful. This is starting to sound like there might be some issue on their side, just not sure what...

**Comment by mirabilos** [comment]
tobi dixit:

>Some logs from that akkoma instance would be helpful. This is starting
>to sound like there might be some issue on their side, just not sure
>what...

Oh, ok. I’ll ask them.

**Comment by tsmethurst** [comment]
Hey @mirabilos , did you have any more movement on this? Is it still an issue?

**Comment by mirabilos** [comment]
as for searching a GtS user from Akkoma: unfortunately, I haven’t heard back from them at all

as for searching an Akkoma user by https from GtS: I can confirm that searching for `https://outerheaven.club/administration` (a random Akkoma account I grabbed, I don’t know them) in Semaphore still yields a 500, after ensuring via `gotosocial=# SELECT username FROM accounts WHERE domain='outerheaven.club' ORDER BY lower(username);` that the user is not already known to my instance.

```
timestamp="2023-10-25T20:43:21.107Z" func=server.glob..func1.Logger.func13.1 level=ERROR latency="220.528097ms" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0" method=GET statusCode=500 path=/api/v2/search error="Error #01: Get: error searching by URI: byURI: error looking up https://outerheaven.club/administration as account: enrichAccount: error resolving accountable from data for account https://outerheaven.club/administration: ResolveAccountable: error unmarshalling bytes into json: invalid character '<' looking for beginning of value\n" requestID=pzas6t4b04001vcgcn8g msg="Internal Server Error: wrote 54B"
```

**Comment by tsmethurst** [comment]
Alright thanks for checking!

**Comment by tsmethurst** [comment]
That 500 response will be closed by https://github.com/superseriousbusiness/gotosocial/pull/2550

The other part of the issue is covered here: https://github.com/superseriousbusiness/gotosocial/issues/2327

**Comment by mirabilos** [comment]
OK, then no need to keep this issue around. Thanks!
